remarkablemark/html-dom-parser

lib/domparser.js
lib/html-to-dom-client.js
test/index.js

Resolves #1
- Modularize `lib/domparser.js` from `lib/html-to-dom-client.js`
- Improve client parser
- Use [template](https://developer.mozilla.org/docs/Web/HTML/Element/template) as a more performant way of parsing HTML without loading external resources like images
- Ensure the parser fallbacks to `DOMImplementation` and then `DOMParser` (based on performance)
- HTML with `<html>` tags will be parsed by `DOMParser`
- Make sure to prune extraneous tags (e.g., `<head>` or `<body>`) if not in the HTML
- Improve regex and create constants
- Fix tests
- [Spike](https://gist.github.com/remarkablemark/c23f93fc4ef1b2a977459b32a46aaafb)

Refactor and improve client parser

---

lib/domparser.js
test/index.js

Fixes #3
- The first parameter for [`createHTMLDocument`](https://developer.mozilla.org/docs/Web/API/DOMImplementation/createHTMLDocument#Parameters) is **required** in IE
- Enable svg tests for client parser (current version of `jsdom` supports svg)

Specify title parameter for `document.implementation.createHTMLDocument`

---

.eslintrc.json
package.json
rollup.config.js

| file | webpack | rollup |
| :--- | :---: | :---: |
| `html-dom-parser.js` | 16.3 KB | 12 KB |
| `html-dom-parser.min.js` | 4.39 KB | 3.3 KB |
| `html-dom-parser.js.map` | - | 20 KB |
| `html-dom-parser.min.js.map` | - | 15 KB |
Include sourcemaps for min and unmin bundles

build(rollup): use rollup to build browser bundle

---

examples/index.html
karma.conf.js
lib/html-to-dom-client.js
lib/html-to-dom-server.js
lib/utilities.js
package.json
test/cases/html.js
test/cases/index.js

- docs: improve JSDoc
- test: remove deprecated PhantomJS from Karma tests
- refactor: rename functions and variable
- chore: update example `index.html`
- JSDoc stale
- Karma test still runs PhantomJS
- Main function is named `parseDOM`
- Improved JSDoc
- Karma test no longer runs PhantomJS (only Chrome)
- Main function is named `HTMLDOMParser`
- Example `index.html` uses better placeholder text

chore: improve docs and tests, refactor code

---

karma.conf.js
test/client/index.js
test/helpers/run-tests.js

test(karma): refactor and update karma client tests
No Mocha HTML reporter for Karma `Debug` page. Client performance test is skipped.
Changed Karma's `debug.html` to the Mocha web reporter. Client performance test enabled.

test(karma): refactor and update karma client tests

---

test/client/index.js
test/helpers/index.js
test/helpers/run-tests.js
test/helpers/throw-errors.js
test/helpers/throws-error.js
test/server/index.js
test/server/server.js

test(helpers): rename and refactor test helpers

test(helpers): rename and refactor test helpers

---

README.md
lib/domparser.d.ts
lib/html-to-dom-client.d.ts
lib/html-to-dom-server.d.ts
test/helpers/cycle.js
test/helpers/run-tests.js
test/helpers/throw-errors.js
test/server/index.js

chore: update README.md and refactor tests and types
- Added `domhandler` link to README
- For test helpers, added [cycle.js](https://github.com/douglascrockford/JSON-js/blob/master/cycle.js), which will be used by Karma client tests later after `htmlparser2` major upgrade
- Improve JSDoc in type declaration files

chore: update README and refactor tests and types

---

karma.conf.js
lib/html-to-dom-client.d.ts
lib/html-to-dom-server.d.ts
lib/html-to-dom-server.js
lib/utilities.d.ts
lib/utilities.js
package.json
test/helpers/run-tests.js
test/server/index.js
test/types/index.test.ts

feat: upgrade `domhandler` to 3.0.0 and `htmlparser` to 4.0.0
```
domhandler    2.4.2  →  3.0.0
htmlparser2  3.10.1  →  4.0.0
```
dependencies:
- [`domhandler`@2.4.2](https://github.com/fb55/domhandler/releases/tag/v2.4.2)
- [`htmlparser2`@3.10.1](https://github.com/fb55/htmlparser2/releases/tag/v3.10.1)
dependencies:
- [`domhandler`@3.0.0](https://github.com/fb55/domhandler/releases/tag/v3.0.0)
- [`htmlparser2`@4.0.0](https://github.com/fb55/htmlparser2/releases/tag/v4.0.0)
Refactored `utilities.formatDOM` (client parser) to use domhandler `DataNode` and `Element` classes.
It comes with additional properties (e.g., `startIndex` and `endIndex`) and getters: https://github.com/fb55/domhandler/blob/v3.0.0/src/node.ts

feat: upgrade `domhandler` to 3.0.0 and `htmlparser` to 4.0.0

---

lib/html-to-dom-server.d.ts
lib/html-to-dom-server.js
lib/utilities.d.ts
lib/utilities.js
package.json
test/types/index.test.ts

feat: upgrade `domhandler` to 3.3.0 and `htmlparser2` to 4.1.0
```
domhandler   3.0.0  →  3.3.0
htmlparser2  4.0.0  →  4.1.0
```
dependencies:
- [`domhandler`@3.0.0](https://github.com/fb55/domhandler/releases/tag/v3.0.0)
- [`htmlparser2`@4.0.0](https://github.com/fb55/htmlparser2/releases/tag/v4.0.0)
dependencies:
- [`domhandler`@3.3.0](https://github.com/fb55/domhandler/releases/tag/v3.3.0)
- [`htmlparser2`@4.1.0](https://github.com/fb55/htmlparser2/releases/tag/v4.1.0)
Replace domhandler `DataNode` with `Comment` and `Text`.

feat: upgrade `domhandler` to 3.3.0 and `htmlparser2` to 4.1.0

---

lib/utilities.d.ts
lib/utilities.js
test/cases/html.js

refactor(utilities): tidy types, JSDoc, and rename variables
Continue in `formatDOM` if nodeType does not match cases
Add additional HTML test cases (title and entities)

refactor(utilities): tidy types, JSDoc, and rename variables

---

karma.conf.js
lib/server/html-to-dom.d.ts
lib/server/html-to-dom.js
lib/server/utilities.d.ts
lib/server/utilities.js
package.json
test/helpers/run-tests.js

BREAKING CHANGE: upgrade `domhandler` to v4 and `htmlparser2` to v6
```
domhandler   3.3.0  →  4.0.0
htmlparser2  4.1.0  →  6.0.0
```
domhandler:
* https://github.com/fb55/domhandler/releases/tag/v4.0.0
htmlparser2:
* https://github.com/fb55/htmlparser2/releases/tag/v5.0.0
* https://github.com/fb55/htmlparser2/releases/tag/v5.0.1
* https://github.com/fb55/htmlparser2/releases/tag/v6.0.0
`decodeEntities` option now defaults to true. `<title>` is parsed correctly. Remove root parent node to keep parser backwards compatible.

build(package): upgrade `domhandler` to v4 and `htmlparser2` to v6

---

lib/client/domparser.js
lib/client/html-to-dom.js
lib/client/utilities.d.ts
lib/client/utilities.js

perf(client): deprecate Internet Explorer 9 (IE9)
Client parser supported IE9.
Client parser no longer supports IE9 (deprecated).

perf(client): deprecate Internet Explorer 9 (IE9)

---

lib/client/domparser.js
test/cases/html.js
test/client/index.js
test/client/utilities.js
test/helpers/index.js
test/helpers/test-case-sensitive-tags.js
test/server/server.js

- test: add and update tests
- refactor: cleanup `domparser` given IE9 deprecation

test: add and update tests, cleanup `domparser` given IE9 deprecation

---

.github/workflows/build.yml
README.md

ci(github): replace Coveralls with Codecov in workflow `build.yml`
Coveralls
Codecov

ci(github): replace Coveralls with Codecov in workflow `build.yml`

---

package.json

Closes #134
Upgrade `htmlparser2` to [7.2.0](https://github.com/fb55/htmlparser2/releases/tag/v7.2.0)
We shouldn't be affected by breaking changes in [7.0.0](https://github.com/fb55/htmlparser2/releases/tag/v7.0.0)
```
htmlparser2  6.1.0  →  7.2.0
```

perf: upgrade dependency htmlparser2 to v7.2.0

---

.github/workflows/build.yml

ci: set Node.js version to 14 in build.yml workflow
Karma failures in #172 and #174
Lock Node.js version since LTS is 16

ci(github): set Node.js version to 14 in build.yml workflow

---

.github/workflows/build.yml
index.mjs
package.json
test/module/index.mjs

Add ES Module support. Relates to #181
No ES Module support
ES Module support

feat: add ES Module support

---

.size-limit.json
index.d.ts
lib/client/constants.d.ts
lib/client/domparser.d.ts
lib/client/html-to-dom.d.ts
lib/client/utilities.d.ts
lib/server/html-to-dom.d.ts
lib/server/utilities.d.ts
package.json

chore: upgrade devDeps and update TS version in declaration files
```
@size-limit/preset-big-lib   5.0.3  →   7.0.8
size-limit                   5.0.3  →   7.0.8
webpack                     4.46.0  →  5.70.0
```
Saved devDependency `@types/estree` due to dtslint error that came from deduped deps and `@rollup/pluginutils@3.1.0`. See [blog post](https://remarkablemark.org/blog/2022/03/19/dtslint-error-estree-has-no-exported-member/)
Updated TypeScript Version from 4.3 to 4.7 in declaration files

chore: upgrade devDeps and update TS version in declaration files

---

.husky/pre-commit
test/types/index.test.ts

Relates to #236, #238, #239, #240
test(types): fix dtslint expect errors
Don't run `npm run lint:dts` in husky pre-commit hook
dtslint errors:
```
Error: /home/runner/work/html-dom-parser/html-dom-parser/test/types/index.test.ts:4:1
ERROR: 4:1   expect  TypeScript@4.7 expected type to be:
(Comment | Element | ProcessingInstruction | Text)[]
got:
(Text | Comment | ProcessingInstruction | Element)[]
```
No dtslint errors

test(types): fix dtslint errors

---

lib/client/domparser.js
lib/client/utilities.d.ts
lib/client/utilities.js

BREAKING CHANGE: remove Internet Explorer (IE11) support
Internet Explorer has been retired on 2022-06-15: https://blogs.windows.com/windowsexperience/2022/06/15/internet-explorer-11-has-retired-and-is-officially-out-of-support-what-you-need-to-know/
Closes #225
IE11 still supported
IE11 is no longer supported

feat(client): remove Internet Explorer (IE11) support

---

lib/client/domparser.js
test/cases/html.js

Fixes #317
https://github.com/remarkablemark/html-react-parser/issues/624
fix(client): ensure head and body with newline are parsed correctly
`head` and `body` with newlines aren't matched correctly with the [regex](https://github.com/remarkablemark/html-dom-parser/blob/v3.0.0/lib/client/domparser.js#L6-L7)
`head` and `body` with newlines are matched correctly with the DOTALL regex

fix(client): ensure head and body with newline are parsed correctly

---

.size-limit.json
lib/client/domparser.js
lib/client/html-to-dom.mjs
test/module/index.mjs

fix(client): correct ECMAScript export in client html-to-dom.mjs
Fixes #334
```
ReferenceError: module is not defined
```
No ReferenceError

fix(client): correct ECMAScript export in client html-to-dom.mjs

---

lib/client/html-to-dom.js
lib/client/html-to-dom.mjs

fix(client): fix import in html-to-dom.mjs
Fixes #337
Relates to https://github.com/remarkablemark/html-react-parser/issues/662
Client error:
```
error - /app/node_modules/html-dom-parser/lib/client/html-to-dom.mjs
Can't import the named export 'formatDOM' from non EcmaScript module (only default export is available)
```
Fixes error

fix(client): fix import in html-to-dom.mjs

---

.size-limit.json
lib/client/utilities.js
test/cases/html.js

Fixes #414
Relates to https://github.com/remarkablemark/html-react-parser/issues/849
`<template>` childNodes is not parsed correctly
`<template>` childNodes are parsed correctly

fix(client): get template content childNodes in utilities formatDOM

---

.size-limit.json
lib/client/utilities.js
test/cases/html.js

Fixes #417
```
TypeError: Cannot read properties of undefined (reading 'length')
at formatDOM (lib/client/utilities.js)
```
Error should no longer be thrown

fix(client): check for "template" in utilities formatDOM

---

README.md

This PR fixes #424 by documenting all the available options for the server parser.
The documentation is currently missing any mention to these options.
All options are clearly documented and links are provided to their original sources in case users require additional in-depth information.

docs(readme): document parser options

---

package-lock.json
package.json

BREAKING CHANGE: bump htmlparser2 from 8.0.2 to 9.0.0
Closes #459
https://github.com/fb55/htmlparser2/releases/tag/v9.0.0

build(deps): bump htmlparser2 from 8.0.2 to 9.0.0

---

package-lock.json
package.json
rollup.config.mjs

```
rollup. 2.79.1  →  4.1.0
```
Replace `rollup-plugin-terser` with `@rollup/plugin-terser`

build(rollup): upgrade rollup to v4 and replace terser plugin

---

.gitignore
esm/client/html-to-dom.d.mts
esm/index.d.mts
esm/server/html-to-dom.d.mts
package.json

fix(esm): fix ESM types by adding .mts declaration files
ESM types are pointing to the CJS extension
Added MTS declaration files in ESM

fix(esm): fix ESM types by adding .mts declaration files

---

src/types.ts

When importing html-dom-parser 5.0.5 from Typescript with `verbatimModuleSyntax` enabled the build fails with:
```
node_modules/.pnpm/html-dom-parser@5.0.5/node_modules/html-dom-parser/esm/types.ts:2:10 - error TS1448: 'Comment' resolves to a type-only declaration and must be re-exported using a type-only re-export when 'verbatimModuleSyntax' is enabled.
2 export { Comment, Element, ProcessingInstruction, Text };
```
Typescript fails
Typescript accepts the input

Fix type re-export

---

esm/index.d.mts

fix(esm): fix exported types
Relates to #669
Exported ESM types do not have extension
Exported ESM types have extension

fix(esm): fix exported types

---

package.json

Many users have bundler issues with this package and the [html-react-parser](https://github.com/remarkablemark/html-react-parser) package that depends on it.  Sometimes it is necessary to change how packages are resolved—for example, to force loading the server version in certain environments.
However, resolving the server version is difficult when importing the package.json is disabled by the package.json exports field.  This patch enables code to import the package.json.
Beyond this bundling use case, I have found importing the package.json may be useful for reading versions, dependencies, and other metadata.
An error is thrown if you try to import the package.json
Importing the package.json is allowed
Thank you for reviewing!

fix: exports field includes package.json

---

src/client/constants.ts
src/client/utilities.ts
test/cases/html.js
test/cases/index.js
test/server/client.test.ts

fix(client): don't break LaTeX when replacing carriage returns
Fixes #917
Related to https://github.com/remarkablemark/html-react-parser/issues/1634
All `\r` are removed from the HTML string, even if the raw string is formatted as `\\r`.
`\\r` is no longer removed.

fix(client): don't break LaTeX when replacing carriage returns

---

package-lock.json
package.json

`npm-run-all` stopped being maintained about 4 years ago.
https://github.com/bcomnes/npm-run-all2

chore: replace npm-run-all with maintained fork
